Kinvey/js-sdk

src/entity/src/user.js
test/unit/entity/user.test.js
test/unit/helpers/src/user.js

[v3.1.0](https://github.com/Kinvey/javascript-sdk-core/releases/tag/v3.1.0) does not allow to login a `User` using the following api syntax. 
```javascript
Kinvey.User.login({
username: '<username>',
password: '<password>'
});
```
- Set default options to an empty object for `Kinvey.User.login()`
- Add unit tests to verify an object can be provided to login a user.

MLIBZ-1322 Can't login user when providing credentials as an object

---

src/entity/src/user.js
test/unit/entity/user.test.js

`forgotUsername()`, `verifyEmail()`, and `resetPassword()` functions on the `User` class should be static and not require an active user to be executed.
- Made `forgotUsername()`, `verifyEmail()`, and `resetPassword()` functions on the `User` class.
- Added unit tests for the changes made on the `User` class.

MLIBZ-1317 Make forgotUsername(), verifyEmail(), and resetPassword() functions on the User class static

---

.travis.yml
package.json
src/kinvey.js
src/request/src/cacherequest.js
src/request/src/networkrequest.js
src/social/src/facebook.js
src/social/src/mic.js

The core needs some shim specific modules in order to function properly. These `kinvey-` modules are replaced with implementations using webpack when a shim is bundled.
- import `kinvey-` modules for shim specific modules.

External Kinvey Modules

---

src/client.js
src/request/src/kinveyrequest.js

Use Device class set on the client instance to set X-Kinvey-Device-Information header
- Set the a `Device` class instance on the client.

Use Device class set on the client instance to set X-Kinvey-Device-Information header

---

src/entity/src/user.js
test/unit/entity/user.test.js

This PR merges the data returned from a login request with the passed in credentials. This prevents from overriding properties that are used by developers.
- Merge data returned from login request with credentials.

MLIBZ-1452 Merge credentials and login data

---

.codeclimate.yml
src/aggregation.js
test/unit/aggregation.test.js

This PR fixes an issue with the provided count aggregation function and how aggregations are calculated.
- Add missing semicolon to count aggregation function
- Refactor how aggregations are calculated
- Add unit tests for aggregations

Fix Aggregation Calculations and Count Aggregation Function

---

src/identity/src/mic.js

This PR removes the check of an error using `instanceof` that is causing a `TypeError`.

Fix TypeError for MIC login

---

src/query.js
test/unit/datastore/syncstore.test.js

Refers to MLIBZ-1557
`skip` and `limit` qualifiers on queries are not working on local cache. This PR fixes the problem; and also fixes `sort` on local queries which was found to not work.
`query.process()` has changes to fix the broken modifiers.
`syncStore.test` has new tests for local queries.
New unit tests added to cover the changes.

Fixes for sort, skip and limit on queries

---

src/client.js
src/errors/src/mobileIdentityConnect.js
src/errors/src/timeout.js
src/request/src/deltafetch.js
src/request/src/request.js

This PR fixes failing unit tests because of changes to Error object.

Fix unit tests

---

src/query.js
test/unit/datastore/networkstore.test.js
test/unit/query.test.js

This PR improves the unit test coverage by adding new tests to query module.
`query.test.js` contains new tests

Improving test coverage

---

src/request/src/network.js
test/unit/entity/user.test.js

Fixes a bug that produces a `TypeError` whenever an `InvalidCredentialsError` is encountered with a `NetworkRequest`.
- Fix code to be synchronous and not to use promise syntax.
- Add test case to catch issue

MLIBZ-1586 Failed login produces a TypeError

---

src/errors/index.js
src/errors/src/popup.js
src/request/src/network.js
src/request/src/response.js
test/unit/mocks/src/user.js
test/unit/request/network.test.js

This PR verifies that we are able to correctly refresh MIC sessions when they have expired.
- Don't retry failed refresh requests when we are in the middle of refreshing a MIC session. [af4ce5f](https://github.com/Kinvey/js-sdk/commit/af4ce5fef3495dff74d418e94b356be60211b73c)
- Add unit tests to verify we can refresh MIC sessions. [9949d11](https://github.com/Kinvey/js-sdk/commit/9949d11855101f10dc99820f9b29cb662b1e68b0).

MLIBZ-1525: Expired Session Crash

---

src/errors/index.js
src/errors/src/apiVersionNotAvailable.js
src/errors/src/apiVersionNotImplemented.js
src/errors/src/appProblem.js
src/errors/src/badRequest.js
src/errors/src/bl.js
src/errors/src/corsDisabled.js
src/errors/src/duplicateEndUsers.js
src/errors/src/indirectCollectionAccessDisallowed.js
src/errors/src/invalidCredentials.js
src/errors/src/invalidIdentifier.js
src/errors/src/kinveyInternalErrorRetry.js
src/errors/src/kinveyInternalErrorStop.js
src/errors/src/parameterValueOutOfRange.js
src/errors/src/staleRequest.js
src/errors/src/userAlreadyExists.js
src/errors/src/writesToCollectionDisallowed.js
src/request/src/middleware/src/http.js
src/request/src/response.js
test/unit/request/response.test.js

This PR adds missing error objects and cleans up code for returning an error from a response.
- Add missing Error Objects. [6fcf28a](https://github.com/Kinvey/js-sdk/commit/6fcf28a7343ad7c91a17dd85be2a77ad9d1a934f) [7804891](https://github.com/Kinvey/js-sdk/commit/7804891abe96cf9d6fa759bff9a6e4706b6cae95)
- Add unit tests for error objects. [916d02d](https://github.com/Kinvey/js-sdk/commit/916d02d83a93e8f480f575a2d0bfa43946cdb2c5) [447f105](https://github.com/Kinvey/js-sdk/commit/447f105809ccaf2420c0bda1776751018e2faf29)

MLIBZ-1507: Error Objects

---

package.json
src/datastore/src/filestore.js
test/unit/datastore/filestore.test.js

This PR fixes a bug that would prevent a file from being uploaded to GCS.
- Handle file upload responses correctly.
- Fix unit tests to ensure all mocked API responses are consumed and promises are either fulfilled or rejected when expected.

MLIBZ-1676: File Upload Bug

---

README.md
package.json

Rename package name and update README

---

package.json
src/request/src/middleware/src/storage/index.js
src/request/src/request.js
test/datastore/syncstore.test.js

When setting the body of a request it should be cloned rather then referenced.
- Clone body of a request.
- Update unit tests.

MLIBZ-1646: Clone body of request

---

src/datastore/src/sync.js
test/datastore/sync.test.js

A user could kick off multiple sync push operations at once causing unexpected behaviors. This PR fixes this bug from preventing multiple sync push operations from being executed at the same time. If a sync push operation is already in progress, other sync push operations will fail immediately and must wait until the current sync push operation completes.
- Add flag to mark if a sync push operation is in progress.
- Add a unit test to ensure only one sync push operation is possible.

MLIBZ-1271: Prevent sync push from being sent when one is already in progress.

---

src/query.js
test/query.test.js

This PR refactors `query.matches()` and adds unit tests.
- Refactor `query.matches()`
- Add unit tests for `query.matches()`

MLIBZ-1759: Query matches RegEx

---

src/client.js
src/entity/src/activeUserHelper.js
src/entity/src/user.js
src/identity/src/mic.js
src/kinvey.js
src/request/src/cache.js
src/request/src/network.js
test/client.test.js
test/entity/user.test.js
test/index.js
test/kinvey.test.js
test/request/cache.test.js

Store active user with native storage

---

src/request/src/middleware/src/cache.js
src/request/src/middleware/src/storage/index.js
src/request/src/middleware/src/storage/memory.js

Replaces all errors to use `KinveyError`. Export `Storage` class not as the default.

MLIBZ-1967: Fix Storage API

---

src/aggregation.js
test/aggregation.test.js

This PR correctly imports the `Query` class in `aggregation.js`.
- Import `Query` class correctly.
- Add unit tests for get/set a query instance on an aggregation instance.

MLIBZ-2060: Fix import statement for Query class in aggregation.js

---

test/unit/live/collection/live-collection-manager.test.js
test/unit/live/nock-helper.js

Fixes unit tests

---

package.json
src/client.js
src/utils/src/string.js

The [uuid](https://www.npmjs.com/package/uuid) package uses the NodeJS [crypto](https://nodejs.org/dist/latest-v6.x/docs/api/crypto.html) module to generate a uuid. On NativeScript, the crypto module is not available. This PR removes the uuid dependency and replaces it with a custom developed uuidv4 function.

Replace UUID 

---

package.json

Use forked version of PubNub

---

packages/kinvey-nativescript-sdk/package.json

Remove nativescript-push-notifications as a dependency

---

packages/kinvey-angular2-sdk/package.json
packages/kinvey-nativescript-sdk/package.json

MLIBZ-2247:  Add rxjs as a dependency to use in definitions file

---

packages/kinvey-angular-sdk/webpack.config.js
packages/kinvey-angular2-sdk/webpack.config.js
packages/kinvey-html5-sdk/webpack.config.js
packages/kinvey-js-sdk/webpack.config.js
packages/kinvey-nativescript-sdk/webpack.config.js
packages/kinvey-node-sdk/webpack.config.js
packages/kinvey-phonegap-sdk/webpack.config.js

This adds the `UglifyJSPlugin` by default to the plugins array. Some cleanup is done to the plugins for options that are not used.

Update webpack.config.js for each SDK

---

src/core/datastore/processors/cache-offline-data-processor.js
src/core/datastore/processors/data-processor.js
src/core/datastore/processors/index.js
src/core/datastore/processors/network-data-processor.js
src/core/datastore/processors/offline-data-processor.js
src/core/datastore/processors/processor-factory.js

Part six of MLIBZ-2238.
Add processors.

Datastores redesign part 6 - processors

---

src/core/datastore/operations/index.js
src/core/datastore/operations/operation-factory.js
src/core/datastore/operations/operation-type.js
src/core/datastore/operations/operation.js
src/core/datastore/processors/cache-offline-data-processor.js
src/core/datastore/processors/data-processor.js
src/core/datastore/processors/index.js
src/core/datastore/processors/network-data-processor.js
src/core/datastore/processors/offline-data-processor.js
src/core/datastore/processors/processor-factory.js

Part five of MLIBZ-2238
Add operation class and factory.

Datastores redesign part 5 - operations

---

src/core/datastore/operations/index.js
src/core/datastore/operations/operation-factory.js
src/core/datastore/operations/operation-type.js
src/core/datastore/operations/operation.js
src/core/datastore/processors/cache-offline-data-processor.js
src/core/datastore/processors/data-processor.js
src/core/datastore/processors/index.js
src/core/datastore/processors/network-data-processor.js
src/core/datastore/processors/offline-data-processor.js
src/core/datastore/processors/processor-factory.js
src/core/datastore/sync/index.js
src/core/datastore/sync/sync-manager-provider.js
src/core/datastore/sync/sync-manager.js
src/core/datastore/sync/sync-operation.js
src/core/datastore/sync/sync-state-manager.js
src/core/datastore/sync/utils.js

Part four of MLIBZ-2238.
Add sync related classes - `SyncManager`, `SyncStateManager`, etc.

Datastores redesign part 4 - sync

---

src/core/datastore/operations/index.js
src/core/datastore/operations/operation-factory.js
src/core/datastore/operations/operation-type.js
src/core/datastore/operations/operation.js
src/core/datastore/processors/cache-offline-data-processor.js
src/core/datastore/processors/data-processor.js
src/core/datastore/processors/index.js
src/core/datastore/processors/network-data-processor.js
src/core/datastore/processors/offline-data-processor.js
src/core/datastore/processors/processor-factory.js
src/core/datastore/repositories/index.js
src/core/datastore/repositories/network-repository.js
src/core/datastore/repositories/offline-repositories/index.js
src/core/datastore/repositories/offline-repositories/inmemory-offline-repository.js
src/core/datastore/repositories/offline-repository.js
src/core/datastore/repositories/repository-provider.js
src/core/datastore/repositories/repository.js
src/core/datastore/repositories/storage-type.js
src/core/datastore/repositories/utils.js
src/core/datastore/sync/index.js
src/core/datastore/sync/sync-manager-provider.js
src/core/datastore/sync/sync-manager.js
src/core/datastore/sync/sync-operation.js
src/core/datastore/sync/sync-state-manager.js
src/core/datastore/sync/utils.js

Part 3 of MLIBZ-2238.
Add repositories.

Datastores redesign part 3 - repositories

---

.travis.yml
packages/kinvey-angular-sdk/.travis.yml
packages/kinvey-angular2-sdk/.travis.yml
packages/kinvey-html5-sdk/.travis.yml
packages/kinvey-nativescript-sdk/.travis.yml
packages/kinvey-node-sdk/.travis.yml
packages/kinvey-phonegap-sdk/.travis.yml

Add an `if` statement that validates if a tag meets criteria to be a deploy tag. Only allow deploys from the master branch.

MLIBZ-2232: Validate Deploys

---

package-lock.json
packages/kinvey-html5-sdk/src/bundle.js
src/core/datastore/cachestore.js
src/core/datastore/cachestore.spec.js
src/core/datastore/datastore.spec.js
src/core/datastore/persisters/index.js
src/core/datastore/persisters/key-value-persister.js
src/core/datastore/persisters/key-value-store-persister.js
src/core/datastore/persisters/memory-key-value-persister.js
src/core/datastore/persisters/websql-key-value-store-persister.js
src/core/datastore/processors/cache-offline-data-processor.js
src/core/datastore/processors/offline-data-processor.js
src/core/datastore/repositories/offline-repositories/index.js
src/core/datastore/repositories/offline-repositories/inmemory-offline-repository.js
src/core/datastore/repositories/offline-repositories/key-value-store-offline-repository.js
src/core/datastore/repositories/repository-provider.js
src/core/datastore/repositories/storage-type.js
src/core/datastore/repositories/utils.js
src/core/datastore/sync/sync-manager.js
src/core/datastore/utils/utils.js
src/core/request/cache.js
src/core/user/user.spec.js
src/html5/cache.js

[MLIBZ-2263](https://kinvey.atlassian.net/browse/MLIBZ-2263) - Added WebSQL persistance. First implemented part of stage 3 of the redesign. For easier review, I'm creating separate PRs for each ticket, into a branch for all of stage 3.
Implement branch of repository/persister combinations for work with key/value stores like IndexedDb. It currently fits the way we use WebSQL and SQLite.General bug fixes. Small improvements on tests.

Datastores redesign - Add WebSQL persistance

---

packages/kinvey-js-sdk/src/bundle.js
src/core/index.js

Please see https://kinvey.atlassian.net/browse/MLIBZ-2313 and https://kinvey.atlassian.net/browse/MLIBZ-2315 that describes the problem that this PR fixes.

MLIBZ-2313 and MLIBZ-2315: Fix exports

---

test/integration/crud-entity/common-crud.test.js

After the fix of mlibz-2156 the behaviour is the same offline and online, so the tests should behave accordingly.

Fixed sort tests after the fix of mlibz-2156

---

src/core/request/cache.js
src/core/request/cache.spec.js

- Added unit test to check that storage providers are correctly set

Hotfix: Use correct config property for setting storage providers 

---

test/integration/tests/utilities.js

Fixed the tests not to fail on a random basis

Fixed cleanUpData not to fail on a random basis

---

.travis.yml
README.md

Added builds on a PR for the following configurations:
HTML5
NativeScript Android
NativeScript iOS
PhoneGap iOS

Added the Integration Shim tests in travis.yml

---

src/kinvey.d.ts

Fixed the typescript def to add a missing property to `RequestOptions`
All existing unit tests pass. This PR involves no code changes, just a `.d.ts` change.

MLIBZ-2348 Added missing RequestOption to typescript def

---

package-lock.json

Updated the package.lock to use the new runner 1.0.3

---

src/core/datastore/cachestore.js
src/core/datastore/cachestore.spec.js
src/core/datastore/datastore.js
src/core/datastore/datastore.spec.js
src/core/datastore/networkstore.spec.js
src/core/datastore/persisters/browser/websql-sql-module.js
src/core/datastore/processors/cache-offline-data-processor.js
src/core/datastore/repositories/network-repository.js
src/core/datastore/repositories/offline-repositories/inmemory-offline-repository.js
src/core/datastore/repositories/offline-repositories/key-value-store-offline-repository.js
src/core/datastore/repositories/repository-provider.js
src/core/datastore/repositories/utils.js
src/core/datastore/sync.spec.js
src/core/datastore/sync/sync-manager.js
src/core/datastore/sync/sync-state-manager.js
src/core/datastore/syncstore.spec.js
src/core/datastore/utils/utils.js
src/nativescript/push/common.ts
src/phonegap/push.js

MLIBZ-2338 and MLIBZ-2346. I figured MLIBZ-2346 isn't large enough to require a PR in itself.
Implement tagged data store feature. Stop skipping tests for it, add a few more unit tests. Also fixed the order of delete and create operations when trying to update the local result of a create() with the network result (CacheStore only).

Datastores redesign stage 4, part 4 - tagged datastores

---

src/core/polyfills/index.js
src/core/polyfills/number.js
src/core/polyfills/number.spec.js
src/core/polyfills/object.js

Add polyfill for Number.isNaN

---

.travis.yml

Added PG Android execution in Travis

---

src/core/identity/mic.js
src/core/identity/mic.spec.js
src/core/request/network.spec.js

Changes the default MIC API version to v3.
- New unit test to check for the right versioned URL 
- Updates to existing tests to use `/v3`

MLIBZ-2378 Change MIC default version to 3

---

src/core/identity/mic.js
src/core/identity/mic.spec.js
src/core/request/network.spec.js

After discussion with @andrewmaillet , we realized that v3 requires a `scope` parameter in the `/oauth/auth` call. This PR adds it.

Add scope parameter to mic for v3.

---

src/core/live/collection/live-collection-manager.js
src/core/live/live-service.js
src/core/live/user-to-user/stream.js

Use es6-promise promises in live-service-related files, instead of native ones.
Add imports for es6-promises.

MLIBZ-2133 Live service promises

---

packages/kinvey-nativescript-sdk/package.json
packages/kinvey-nativescript-sdk/runner-config.js

Added back for execution the NS tests for Files

---

src/core/request/network.js
src/core/request/network.spec.js

TypeError: undefined is not an object (evaluating 'activeUser._kmd.authtoken')
```
file:///app/tns_modules/kinvey-js-sdk/dist/request/src/network.js:151:35: JS ERROR TypeError: undefined is not an object (evaluating 'activeUser._kmd.authtoken')
```
- Use `isPlainObject()` to verify `activeUser._kmd` is an object
- Add unit tests to check errors are thrown for invalid active user states
- Add unit test to verify an `Authorization` header is created properly for a valid active user

MLIBZ-2552: Fix error caused by trying to access a property on an undefined object

---

test/integration/tests/sync.test.js

Qa 240 sync with query

---

packages/kinvey-html5-sdk/src/index.js
packages/kinvey-html5-sdk/src/indexeddb.js
packages/kinvey-html5-sdk/src/popup.js
packages/kinvey-html5-sdk/src/session.js
packages/kinvey-html5-sdk/webpack.config.js
packages/kinvey-js-sdk/src/cache.js
packages/kinvey-js-sdk/src/datastore/cachestore.js
packages/kinvey-js-sdk/src/datastore/index.js
packages/kinvey-js-sdk/src/datastore/networkstore.js
packages/kinvey-js-sdk/src/http/headers.js
packages/kinvey-js-sdk/src/http/index.js
packages/kinvey-js-sdk/src/http/request.js
packages/kinvey-js-sdk/src/http/session.js
packages/kinvey-js-sdk/src/identity/index.js
packages/kinvey-js-sdk/src/identity/mic.js
packages/kinvey-js-sdk/src/identity/popup.js
packages/kinvey-js-sdk/src/identity/user.js
packages/kinvey-js-sdk/src/index.js
packages/kinvey-js-sdk/src/observable.js
packages/kinvey-js-sdk/tests/acl.spec.js
packages/kinvey-js-sdk/tests/kmd.spec.js

Refactor: Fix Tests and Update APIs

---

packages/kinvey-nativescript-sdk/package.json
packages/kinvey-node-sdk/package-lock.json
src/nativescript/nativescript-sql-module.ts
src/nativescript/offline-data-storage.ts

Add encryption for SQLite on NativeScript.
- Use `encryptionKey` to open the SQLite database.

MLIBZ-2649: Use encryptionKey to encrypt SQLite database on NativeScript

---

packages/kinvey-nativescript-sdk/push.d.ts

Added missing TypeScript definitions to NativeScript Push

MLIBZ-2684: Update TypeScript definitions for NativeScript Push

---

packages/kinvey-js-sdk/src/endpoint.js
packages/kinvey-js-sdk/src/index.js
packages/kinvey-js-sdk/tests/endpoint.spec.js

MLIBZ-2596: Custom Endpoint

---

packages/kinvey-nativescript-sdk/kinvey.d.ts

count methods return a number instead of an object of the form {count:number}

fixing count return values

---

tests/integration/shared/endpoint.spec.js

Added integration tests for CustomEndpoint

---

src/http/request.js

MLIBZ-2875: Fix issue with refreshing MIC access token

---

scripts/build.angular.js
scripts/build.html5.js
scripts/build.js
scripts/build.nativescript.js
scripts/build.node.js
src/datastore/networkstore.js
src/device/index.html5.js
src/device/index.js
src/device/index.nativescript.js
src/device/index.node.js
src/live/index.html5.js
src/live/index.nativescript.js
src/live/index.node.js
src/live/live.js
src/user/user.js

MLIBZ-2905: Live Service

---

src/datastore/cachestore.js

MLIBZ-2925: Find with query does not clear items from cache that have been deleted or changed on the backend

---

src/user/user.js

MLIBZ-2929: If the active user is deleted from the backend, the user cannot be logged out

---

package-lock.json
package.json

I have added [PubNub](https://www.npmjs.com/package/pubnub) as a dependency.

MLIBZ-2926: Bundling the HTML5 SDK fails because of uninstalled peerDependencies

---

tests/html5/tests/init.spec.js
tests/shared/users.spec.js

fix init and signupWithIdentity tests

---

tests/shared/common-crud.spec.js

fixed some crud integration tests

---

packages/kinvey-nativescript-sdk/lib/before-preview-sync.js
src/nativescript/user.js

There are two preview apps - NS and Kinvey Studio, and each has its own scheme. Add support for the Kinvey Studio preview app.

Add support for the new KS preview app scheme

---

tests/integration/specs/common/aggregation.spec.js
tests/integration/specs/common/auth.spec.js
tests/integration/specs/common/common-crud.spec.js
tests/integration/specs/common/delta-set.spec.js
tests/integration/specs/common/endpoint.spec.js
tests/integration/specs/common/files.spec.js
tests/integration/specs/common/live-services.spec.js
tests/integration/specs/common/offline-crud.spec.js
tests/integration/specs/common/sync.spec.js
tests/integration/specs/common/users.spec.js
tests/integration/specs/utils.js

Added ability to run tests with different offline providers

---

packages/html5-sdk/src/init.ts
packages/js-sdk/src/init.ts
packages/nativescript-sdk/src/nativescript/init.ts
packages/node-sdk/src/init.ts

- Add `_storage` property
- Add `deviceId` property

MLIBZ-2981: Return missing properties from init()

---

packages/js-sdk/package.json
packages/js-sdk/src/datastore/networkstore.ts
packages/js-sdk/src/http/headers.ts
packages/js-sdk/src/kinvey.ts
packages/js-sdk/test/datastore/autostore.spec.ts
packages/js-sdk/test/datastore/save.spec.ts

Adds support for creating an array of docs to using the Kinvey backend API.

MLIBZ-3016: Multi Record Insert

---

packages/js-sdk/src/user/loginWithMICUsingResourceOwnerCredentials.ts
packages/js-sdk/src/user/mic/getTokenWithCode.ts
packages/js-sdk/src/user/mic/getTokenWithUsernamePassword.ts
packages/js-sdk/test/mic/mic.spec.ts

MLIBZ-2889: Add version to MIC urls

---

packages/nativescript-sdk/angular/index.d.ts
packages/nativescript-sdk/angular/push.d.ts

Without this file no typings will be loaded when you use:
```
import { UserService } from 'kinvey-nativescript-sdk/angular';
import { KinveyPushModule } from 'kinvey-nativescript-sdk/angular/push';
```
You will have no autocomplete when importing `kinvey-nativescript-sdk/angular` or `kinvey-nativescript-sdk/angular/push`

Create index.d.ts and push.d.ts

---

packages/nativescript-sdk/package-lock.json
packages/react-native-sdk/.editorconfig
packages/react-native-sdk/.gitignore
packages/react-native-sdk/CONTRIBUTING.md
packages/react-native-sdk/LICENSE
packages/react-native-sdk/README.md
packages/react-native-sdk/code-of-conduct.md
packages/react-native-sdk/package-lock.json
packages/react-native-sdk/package.json
packages/react-native-sdk/src/index.ts
packages/react-native-sdk/src/init.ts
packages/react-native-sdk/tsconfig.json

MLIBZ-3037: Create kinvey-react-native-sdk package

---

packages/react-native-sdk/package-lock.json
packages/react-native-sdk/package.json
packages/react-native-sdk/src/httpAdapter.ts
packages/react-native-sdk/src/init.ts
packages/react-native-sdk/tsconfig.json

MLIBZ-3061: Add http adapter to kinvey-react-native-sdk

---

packages/js-sdk/src/kinvey.ts
packages/js-sdk/test/kinvey.spec.ts

MLIBZ-2966: Add colon to auth and baas protocols

---

package-lock.json
packages/js-sdk/src/live.ts
packages/nativescript-sdk/src/nativescript/init.ts
packages/nativescript-sdk/src/nativescript/live.ts
packages/nativescript-sdk/src/nativescript/sessionStore.ts

Live services do not resume receiving updates after connection problems are resolve. This fixes that issue by monitoring the network connectivity and reconnecting `PubNub`.
- Monitor network connectivity and reconnect to `PubNub`

MLIBZ-2999: Monitor network connection and reconnect PubNub

---

.cirrus.yml
packages/react-native-sdk/jest.config.js
packages/react-native-sdk/jest/setup.ts
packages/react-native-sdk/src/storage/__tests__/asyncStorage.spec.ts
packages/react-native-sdk/tsconfig.jest.json

Setup React Native SDK Tests

---

packages/react-native-sdk/README.md

Update react-native-sdk README

---

.gitignore
packages/js-sdk/jest.config.js
packages/js-sdk/src/user/remove.ts
packages/js-sdk/test/datastore/autostore.spec.ts
packages/js-sdk/test/datastore/save.spec.ts
packages/js-sdk/test/kinvey.spec.ts
packages/js-sdk/test/mic/mic.spec.ts
packages/js-sdk/test/query.spec.ts
packages/js-sdk/test/user/signup.spec.ts
packages/js-sdk/test/user/user.spec.ts
packages/nativescript-sdk/package-lock.json
packages/node-sdk/package-lock.json
tests/integration/node/mocha.opts
tests/integration/specs/common/aggregation.spec.js
tests/integration/specs/common/delta-set.spec.js
tests/integration/specs/common/live-services.spec.js
tests/integration/specs/common/users.spec.js
tests/integration/specs/utils.js

Some integration tests were failing when run locally. I've reviewed the suites one by one and made adjustments where necessary, mainly in before/after hooks. Now all tests pass except about 10 data store tests related to a query skip/take bug.

KDEV-295: Fixes for integration tests

---

packages/angular-sdk/package-lock.json
packages/eslint-config/package-lock.json
packages/html5-sdk/package-lock.json
packages/js-sdk/package-lock.json
packages/node-sdk/package-lock.json

1. Updates several modules in order to address security issues

KDEV-62: Npm security audit

---

packages/js-sdk/src/datastore/sync.ts
packages/js-sdk/src/kinvey.ts
packages/js-sdk/test/datastore/autostore.spec.ts
tests/integration/specs/common/autostore.spec.js
tests/integration/specs/common/common-crud.spec.js
tests/integration/specs/utils.js

Changes:
* Use API v5 by default
* Use batch create only when inserting more than 1 item at a time

KDEV-400: Switch default API version to 5

---

packages/angular-sdk/package-lock.json
packages/html5-sdk/package-lock.json
packages/js-sdk/package-lock.json
packages/js-sdk/src/datastore/cachestore.ts
packages/js-sdk/src/datastore/networkstore.ts
packages/js-sdk/test/datastore/autostore.spec.ts
packages/js-sdk/test/datastore/networkstore.spec.ts
packages/js-sdk/test/datastore/syncstore.spec.ts
packages/nativescript-sdk/package-lock.json
packages/node-sdk/package-lock.json

Added validations for `create` function:
* Sync, Auto, Network store: Empty array provided.
* Sync, Auto store: Entities with duplicate `_id` values within the array.
* Sync, Auto store: Entities with `_id` values that already exist in the local cache.

KDEV-557, KDEV-558, KDEV-866, KDEV-867: Multi-insert validations

---

.vscode/settings.json
packages/nativescript-sdk/package-lock.json
packages/nativescript-sdk/package.json
packages/nativescript-sdk/reference.d.ts
packages/nativescript-sdk/src/angular/kinvey.module.ts
packages/nativescript-sdk/src/nativescript/files/upload.ts
packages/nativescript-sdk/src/nativescript/httpAdapter.ts
packages/nativescript-sdk/src/nativescript/live.ts
packages/nativescript-sdk/src/nativescript/popup/popup.android.ts
packages/nativescript-sdk/src/nativescript/popup/popup.ios.ts
packages/nativescript-sdk/src/nativescript/push.ts
packages/nativescript-sdk/src/nativescript/sessionStore.ts
packages/nativescript-sdk/src/nativescript/user/loginWithRedirectUri.ts
packages/nativescript-sdk/src/nativescript/utils.ts
packages/nativescript-sdk/tsconfig.json

Adds support for NativeScript 7
- update tsconfigs
- update imports
- update dependencies for dev and plugin

Feat: NativeScript 7 Support

---

packages/js-sdk/src/user/user.ts
tests/integration/specs/common/users.spec.js

See description and comment: https://github.com/Kinvey/js-sdk/pull/594

KDEV-1589: Do not use authToken in me method

---

packages/js-sdk/src/user/loginWithMFA.ts
tests/integration/specs/common/users.spec.js

KDEV-1751: Limit mfaComplete calls

---

packages/js-sdk/src/user/user.ts

KDEV-1759: Clean entire session store when calling invalidateTokens

---

packages/js-sdk/src/user/loginWithMFA.ts

KDEV-1575: Clean MFA token after successful login

---

packages/js-sdk/src/kinvey.ts

Change default API version to 6

---

packages/angular-sdk/src/user.service.ts
packages/nativescript-sdk/src/angular/user.service.ts

KDEV-1770: Fix angular and ns build

---

tests/integration/specs/common/auth.spec.js

Fix auth tests

---

packages/angular-sdk/src/index.ts
packages/angular-sdk/src/user.service.ts
packages/nativescript-sdk/src/angular/user.service.ts

KDEV-1776: Add missing interfaces to ng; add loginWithRecoveryCode to ng and ns

---

packages/angular-sdk/src/index.ts
packages/angular-sdk/src/mfa.service.ts

KDEV-1776: Expose MFAService from angular-sdk

---

packages/js-sdk/src/user/user.ts
tests/integration/specs/common/mfa.spec.js

KDEV-1778: Limit createAuthenticator verification retries

---

packages/js-sdk/src/http/headers.ts
packages/js-sdk/src/http/session.ts
packages/js-sdk/src/mfa/index.ts
packages/js-sdk/src/user/createMFAAuthenticator.ts
packages/js-sdk/src/user/loginWithMFA.ts
packages/js-sdk/src/user/user.ts
tests/integration/specs/common/mfa.spec.js
tests/integration/specs/utils.js

* Support authenticator creation with MFA session token - to do so, start saving not only the MFA session token but the user ID, too
* Add MFA enabled check and MFA disable functionality on the User class

KDEV-1796: KDEV-1800: Improve MFA logic

---

tests/integration/specs/common/users.spec.js

Expect authtoken only if active user

---

packages/js-sdk/package-lock.json
packages/js-sdk/src/http/request.ts
packages/js-sdk/src/http/session.ts
packages/js-sdk/test/mic/session-management.test.ts
packages/nativescript-sdk/package-lock.json
packages/node-sdk/package-lock.json
packages/react-native-sdk/package-lock.json
tests/integration/package-lock.json
tests/integration/package.json
tests/integration/specs/common/users.spec.js
tests/integration/specs/utils.js

* The PR adds cleaning up the active user and stores when an InvalidCredentials error occurs and a valid access token cannot be acquired. It intends to bring [this improvement](https://github.com/Kinvey/js-sdk/pull/638) to the 5.x.x version of the SDK. The code is mostly the same but there are some slight differences here and there.
**Note:** I've created a branch from the 5.1.4 tag.

KDEV-2693: Clear active user on InvalidCredentials
