src/aggregation.js, src/datastore/src/cachestore.js, src/datastore/src/networkstore.js, src/datastore/src/syncstore.js, src/export.js, src/kinvey.js, src/request/src/middleware/src/cache.js, src/request/src/middleware/src/storage/index.js, src/request/src/network.js, test/unit/datastore/networkstore.test.js
This PR fixes a bug with grouping on the SDK. When trying to perform a group request, the SDK responds with the following error
```
{ 
description: 'One of more identifier names in the request has an invalid format'
debug: 'The entityName in the request starts with an _ (underscore)',
code: 400 
}
```
- Send a group request with a `POST` and not a `GET`
- Set the aggregation on the request object
- Include the reduce function as a `reduce` property on the object representation of an aggregation
- Add unit test for grouping
=> MLIBZ-1531 Grouping does not work

src/datastore/src/networkstore.js
This PR fixes the misspelling of `complete` in the NetworkStore class.
- Change `compelete` to `complete`.
=> Fix misspelling of complete in NetworkStore

src/entity/src/user.js, test/unit/entity/user.test.js
This PR fixes an issue where the SDK does not merge `_socialIdentity` on a login.
- Merge all identities on `_socialIdentity`
- Update related unit tests
=> MLIBZ-1452: _socialIdentity.kinveyAuth.id is missing from MIC Login

src/request/src/deltafetch.js, test/unit/request/deltafetch.test.js
This PR fixes a bug that prevents using delta fetch with a query.
- Use setter to set skip and limit properties for a query.
- Update unit tests for delta fetch.
=> Fix bug that prevents using delta fetch with a query

src/errors/index.js, src/errors/src/activeUser.js, src/errors/src/base.js, src/errors/src/featureUnavailable.js, src/errors/src/incompleteRequestBody.js, src/errors/src/insufficientCredentials.js, src/errors/src/invalidCredentials.js, src/errors/src/invalidIdentifier.js, src/errors/src/invalidQuerySyntax.js, src/errors/src/jsonParse.js, src/errors/src/kinvey.js, src/errors/src/missingQuery.js, src/errors/src/missingRequestHeader.js, src/errors/src/missingRequestParameter.js, src/errors/src/noActiveUser.js, src/errors/src/noNetworkConnection.js, src/errors/src/noResponse.js, src/errors/src/notFound.js, src/errors/src/parameterValueOutOfRange.js, src/errors/src/query.js, src/errors/src/server.js, src/errors/src/sync.js, src/request/src/response.js, test/unit/errors/activeUser.test.js, test/unit/request/kinveyrequest.test.js
This PR adds `X-Kinvey-Request-Id` to errors. You can view the `X-Kinvey-Request-Id` related to a specific error by accessing the `kinveyRequestId` property on an error object.
```javascript
asyncNetworkCall()
.catch(function(error) {
// error.kinveyRequestId
});
```
- Add `X-Kinvey-Request-Id` to error objects.
- Add unit tests to check if `X-Kinvey-Request-Id` is set properly on an error object.
=> Add X-Kinvey-Request-Id to errors

src/datastore/src/cachestore.js, src/datastore/src/sync.js, test/unit/datastore/syncstore.test.js
Refers to MLIBZ-1553
On the `SyncStore`, the `sync()` method fails to persist the entities that are pulled from the backend. The `pull()` method works as intended.
The solution is to not delegate `sync()` to the `syncManager`, but instead implement it in the store itself. This way, the `push` and `pull` methods of the store get used.
Added a new unit test for `store.sync()`.
=> Bugfix for sync() not persisting pulled entities

src/errors/index.js, src/errors/src/activeUser.js, src/errors/src/base.js, src/errors/src/featureUnavailable.js, src/errors/src/incompleteRequestBody.js, src/errors/src/insufficientCredentials.js, src/errors/src/invalidCredentials.js, src/errors/src/invalidIdentifier.js, src/errors/src/invalidQuerySyntax.js, src/errors/src/jsonParse.js, src/errors/src/kinvey.js, src/errors/src/missingQuery.js, src/errors/src/missingRequestHeader.js, src/errors/src/missingRequestParameter.js, src/errors/src/noActiveUser.js, src/errors/src/noNetworkConnection.js, src/errors/src/noResponse.js, src/errors/src/notFound.js, src/errors/src/parameterValueOutOfRange.js, src/errors/src/query.js, src/errors/src/server.js, src/errors/src/sync.js, src/request/src/response.js, test/unit/errors/activeUser.test.js
This PR fixes many issues with Error objects. It sets the name property to the correct name of the error. It adds the `X-Kinvey-Request-Id` as a property on the error.
- Set `name`property to name of the error.
- Add `BaseError` extended by all custom errors.
- Add unit test to check if `X-Kinvey-Request-Id` is set properly for an error.
=> Feedback on Error Object

src/datastore/src/userstore.js, src/entity/src/user.js, src/request/src/network.js, test/unit/entity/user.test.js
This PR updates the active user data if a `PUT` request is made to update the user on the backend.
- Update active user data with data returned from `PUT` request made on the active user to the backend.
- Add unit tests for updating a user.
=> MLIBZ-1604: Update a user causes 401 on subsequent API requests

src/datastore/src/userstore.js, src/entity/src/user.js, test/unit/datastore/userstore.test.js, test/unit/entity/user.test.js
This PR adds the ability to discover users using the SDK.
- Override the `find()` function in the `UserStore` class to use the user discover api.
- Add a static `find()` function to the `User` class that proxy calls to the `UserStore`.
- Default all options to an empty object on the `User` class. Fixes MLIBZ-1579.
- Add unit tests for user discovery.
=> MLIBZ-1614: User Discovery

src/entity/src/acl.js, src/entity/src/metadata.js, test/unit/entity/acl.test.js, test/unit/entity/metadata.test.js
This PR fixes errors when trying to use `Kinvey.Acl` and `Kinvey.Metadata` with invalid objects.
- Create an `_acl` property when a provided entity to `Kinvey.Acl` does not contain an `_acl` property.
- Create an `_kmd` property when a provided entity to `Kinvey.Metadata` does not contain an `_kmd` property.
- Don't default entities to an empty object for `Kinvey.Acl` and `Kinvey.Metadata`.
- Update/Add related tests for `Kinvey.Acl` and `Kinvey.Metadata`.
=> MLIBZ-1576: Kinvey V3 add acl to individual entity error

src/entity/src/user.js, src/request/src/cache.js, test/unit/entity/user.test.js
This PR removes sensitive data from locally stored user objects.
- Delete password from data returned from API calls for `login()` and `me()`
- Delete password from data stored for active user
- Update related unit tests
=> MLIBZ 1602: Remove password (hashes) from locally stored User object

package.json, src/datastore/src/filestore.js, src/datastore/src/networkstore.js, src/datastore/src/sync.js, src/datastore/src/userstore.js, src/entity/src/user.js, src/identity/src/facebook.js, src/identity/src/identity.js, src/identity/src/mic.js, src/request/src/cache.js, src/request/src/deltafetch.js, src/request/src/middleware/src/http.js, src/request/src/middleware/src/middleware.js, src/request/src/middleware/src/parse.js, src/request/src/middleware/src/serialize.js, src/request/src/middleware/src/storage/index.js, src/request/src/middleware/src/storage/src/memory.js, src/request/src/network.js, src/request/src/rack.js, src/utils/src/observable.js, test/unit/mocks/src/user.js
This PR removes the use of the es6-promise dependency. NodeJs has [basic support](http://node.green/#Promise) for Promises all the way back to 0.12.18. All other shims can include a shim to add Promise support to the bundle with webpack.
- Remove use of es6-promise.
=> Remove the use of es6-promise

test/unit/entity/user.test.js, test/unit/mocks/src/user.js
This PR adds unit tests for user logout.
- Add unit tests for user logout.
=> MLIBZ-1626: Add unit tests for user logout

src/datastore/src/userstore.js, src/entity/src/user.js, test/entity/user.test.js
Adds a new method to the `User` class to remove user by ID.
- New `removeById()` method implemented in `UserStore`. The implementation includes option `hard=true`, which permanently deletes the user.
- New `remove(id)` static method in `User`, which directs to the `UserStore`.
- Tests to cover new APIs.
- New tests added for new APIs.
- Tested with an Angular sample app.
=> Add method to remove user by id.

src/shims/backbone/persistence/net.js
Issue describe here https://bugs.jquery.com/ticket/8417. By specifying `dataType: json` when sending a `POST` request using jQuery ajax that contains `??` in the body, the request is transformed to a `GET` request.
- Remove `dataType: json`
=> MLIBZ-1089: Sending a POST request with `??` causes the request to be sent as a GET with Backbone

src/datastore/src/filestore.js
We should always default to using `https` urls by default when looking up files.
- use `tls: true` as default for finding files
=> Use tls: true as default when finding files

src/datastore/src/sync.js, test/datastore/sync.test.js
This PR allows sync to push entities to the backend simultaneously on different collections. If a sync push operation is attempted on a collection while one already is in progress for that same collection for then it will be rejected.
- Make `pushInProgress` flag a [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) that uses the collection as a key.
- Add a test to ensure that a sync push operation can be made at the same time on two different collections.
=> MLIBZ-1779: Allow sync to push on different collections at the same time

src/datastore/src/cachestore.js, src/datastore/src/sync.js, test/datastore/syncstore.test.js
This PR allows a user to push only entities in the sync table matching the provided query.
- Find entities that match the query provided before pushing entities to the backend.
- Add a unit test to verify only entities matching the query are pushed.
=> Sync with query

src/entity/src/user.js, src/identity/src/mic.js
This PR adds a function to the `User` class to overwrite the Popup class used for Mobile Identity Connect. Right now, a build tool such as [Webpack](https://webpack.github.io/) is used to replace the popup class used at the time a bundle is generated. This PR would eliminate the need for this.
- Add `usePopupClass()` function to the `User` class.
=> A function to overwrite Popup class

src/request/src/cache.js, test/entity/user.test.js, test/mocks/src/user.mock.js, test/request/cache.test.js
This PR fixes a bug with updating an active user. If multiple requests were sent concurrently to update the active user, some requests might fail because for a short time period the active user is `null`.
Fixes https://github.com/Kinvey/html5-sdk/issues/13.
- Update active user immediately so that other requests can use the new active user.
- Keep setting of active user in order using a queue.
- Add tests for this bug.
=> MLIBZ-1840: Active User Bug

src/client.js, test/client.test.js
Add a valid protocol to `apiHostname` and `micHostname` if either does not contain one.
- Use a regex to test for `https://` or `http://`
- Add tests to set `apiHostname` and `micHostname` to hostnames contains valid and invalid protocols.
=> MLIBZ-1766: Add missing protocol for custom hostnames

package.json, src/datastore/src/cachestore.js
This PR imports the `es6-promise` library to fix `undefined` for promises on platforms that do not have native support for promises.
- Import `es6-promise` for the `CacheStore`
=> MLIBZ-1870: Fix Promise Undefined Bug

package.json, src/identity/src/mic.js, src/request/src/cache.js, test/datastore/syncstore.test.js
This PR should fix MLIBZ-1919 and MLIBZ-1677.
Parse path segments for cache requests manually and remove library from dependencies. Add library for joining URLs and ensure paths don't start with multiple slashes, because that broke the assertions in the tests due to discrepancies between mocked URLs and requested URLs.
Added new test for "." in _id. Old tests pass.
@thomasconner Other special characters seem to fail. If you want to release today, you might take a look. Otherwise I will work it out on Monday.
=> Fix URL formation on Windows and URL symbols in custom ID breaking cache storage

package.json, src/request/src/cache.js, test/datastore/syncstore.test.js
This is related to MLIBZ-1958. Setting environment variables has different syntax on Windows so I removed the setting of BABEL_ENV variable from the build command since it is in the .env file anyways. Babel doesn't seem to have any settings depending on its environment though, so this seems redundant.
Also altered the test for special symbols in the _id field slightly, to only create one item with all special symbols we agreed upon with Tejas.
No changes to the SDK itself, only to the build command and one test, as described above.
=> Sdk on windows

src/client.js, src/datastore/src/filestore.js, src/request/src/response.js, test/client.test.js
***This PR features code which is merely a patch for another issue (the URL building). This is to keep the branch usable for the time being. This part of the PR (its first commit) is not meant to be merged so it's marked as WIP.***
Part of the fix for MLIBZ-1965. NativeScript http module can (by design) only upload strings. A plugin will be used for files. Changes here were necessary since all of the file upload functionality was here, in the core SDK. This PR makes it possible to override the smallest necessary part of the upload process.
Refactored upload() method of FileStore class. Broke it up into smaller pieces in order to override one in a descendant class in NativeScript SDK. Namely, the makeUploadRequest() method.
Old tests pass (with the exception of 9 which fail due to URL …
=> [WIP] Refactor file upload

src/identity/src/mic.js, test/identity/mic.test.js
Allows a user to provide optionally a `micId` that will be included with the `client_id` when attempting to login or refresh a token with MIC.
- Set `client_id` to `appKey:micId` if a `micId` is provided
- Added 2 tests. The first test checks that MIC ignores any invalid `micId`. The second test checks that the `client_id` is formatted correctly to include a `micId`.
=> MLIBZ-1835: Add micId to client_id used for MIC

package.json, src/query.js, src/request/src/cache.js, src/request/src/middleware/src/storage/index.js, src/request/src/network.js, src/request/src/rack.js, src/request/src/request.js, src/request/src/response.js, src/utils/src/log.js
This PR adds logging to the SDK.
- Log outgoing requests and incoming responses.
- Log active user activity.
- Log queries.
=> MLIBZ-1802: Logs

src/utils/src/url.js, test/utils/url.test.js
We use a utility method to append queries in the SDK. This method was adapted from a node package "append-query". 
Recently we've seen an issue with queries in URLs not being properly encoded. Previously, the issue was mis-diagnosed to be in the {N} shim, but it turns out the `appendQuery` is the culprit. 
This PR fixes the issue.
- Minor change in `appendQuery` to fix a typo.
- Tests
- New tests to cover `appendQuery`.
- Manual test on {N} app to confirm the encoding fix.
=> Fix for URL / query encoding issues

src/kinvey.js
`Kinvey.initialize()` will resolve with an instance of a `Kinvey.User` or `null`. 
- Use the `User` class to resolve with the current active user or `null` for `Kinvey.initialize()`.
=> Fix Kinvey.intialize() to resolve with an instance of Kinvey.User or null

src/kinvey.js, src/live/collection/live-collection-manager.js, src/live/live-service-facade.js, src/live/live-service.js, src/live/user-to-user/stream-acl.js, src/live/user-to-user/stream.js, test/live/collection/live-collection-manager.test.js, test/live/live-service-facade.test.js, test/live/live-service.test.js, test/live/nock-helper.js, test/live/user-to-user/stream.test.js, test/live/utilities.js
Small improvements and refactoring for live service related code. If we wish to keep the `unsubscribeFromAll()` method public, we should make it more user friendly, since it now puts the `LiveService` class in an inconvenient state.
Add `getACL()` method for `Stream` class.  Small refactoring and jsdoc adjustments. Remove potentially problematic method `unsubscribeFromAll()`.
Add tests for the new `getACL()` method. Remove tests for the (now private) `_unsubscribeFromAll()` method of `LiveService` class. All remaining tests pass.
=> Live service improvements

src/identity/src/mic.js, test/identity/mic.test.js
In response to a change in the backend, the micId separator is now a `.` character instead of `:`.
Changed existing tests.
=> Changed separator for micID from : to .

src/live/user-to-user/stream-acl.js
Handles MLIBZ-2100 and MLIBZ-2101.
Fix `StreamACL` validation check to allow passing User objects to the class's methods. Add methods for removing subscribers, publishers and groups of them.
`StreamACL` was meant to accept `User` objects but the validation added later on didn't take that into account. Remove methods were missing because there used to be no ability to get the current ACL, so you only ever needed to build new ACL objects.
Amended the validation check when. Add methods for removing subscribers, publishers and groups of them.
All tests pass. None were added, even though we should, at some point.
=> StreamACL class fixes and improvements

src/nativescript/client.ts
This should fix MLIBZ-2150.
Remove redundant modifications of the value to be saved before saving it, when setting the active user. They are present in the set() methods of SecureStorage for both Android and iOS. I misunderstood them last time and that caused a different bug.
=> MLIBZ-2150 Fix setting active user in NativeScript SDK

package-lock.json, package.json, src/html5/storage/websql.js, src/html5/storage/websql.spec.js
Add validation check to `datastore.findById()` for `id` argument. Throw a `NotFoundError` if the `id` argument is not defined.
Updated unit tests for each datastore type to check if a `NotFoundError` is thrown when the `id` argument is not defined.
=> MLIBZ-2225: datastore.findById() should throw a NotFoundError if the id argument is not defined

package-lock.json, package.json, packages/kinvey-nativescript-sdk/webpack.config.js, packages/kinvey-node-sdk/package.json
Replace the `import 'pubnub'` with `import 'pubnub/lib/nativescript'` using webpack.
=> Use NativeScript PubNub with kinvey-nativescript-sdk

src/core/query.js, src/core/query.spec.js
A query will now remove fields after applying the sorting when processing data.
I added 2 new unit tests. The first test checks that a query sorts the data in ascending order correctly when the sorting is applied to a field that is removed. The second test checks that a query sorts the data in descending order correctly when the sorting is applied to a field that is removed.
=> MLIBZ-2154: Remove fields when processing query after sorting data

src/core/query.js, src/core/query.spec.js
I added a condition to the `if` statement in the `addFilter()` function for a query to handle the special use case for `$ne`.
I added a unit tests that verifies that a `$ne` query filters data correctly.
=> MLIBZ-2157: Add filter for a not equal query properly

packages/kinvey-html5-sdk/runner-config.js, packages/kinvey-html5-sdk/test/config.js, test/.eslintrc, test/integration/crud-entity/common-crud.test.js, test/integration/crud-entity/offline-crud.test.js, test/integration/setup.js, test/integration/sync.test.js, test/integration/users/users.tests.js, test/integration/utilities.js
This fixes linting errors in the integration tests. Part of [QA-135](https://kinvey.atlassian.net/browse/QA-135).
Extended `.eslintrc` for the integration tests folder, declaring some globally used variables and turning off some rules, which IMO either didn't make sense or were incompatible with `chai`. Fixed linting errors in test files and utility files for tests. Removed a couple of unused variables from `runner-config.js` and fixed indentation.
=> QA-135 Fix linting errors in integration tests.

src/core/datastore/cachestore.js, src/core/datastore/networkstore.js, src/core/datastore/sync.js, src/core/datastore/sync.spec.js, src/core/datastore/syncstore.js, src/core/datastore/syncstore.spec.js, src/core/request/cache.js, src/core/request/deltafetch.js
- Added `options.tag` to `Kinvey.DataStore.collection()`. This allows a datastore to interact with a subset of entities in the cache for a collection without providing a query each time.
```javascript
const datastore = Kinvey.DataStore.collection('books', Kinvey.DataStoreType.Cache, { tag: 'Kinvey' });
datastore.find(); // This will find all the books tagged as 'Kinvey' on the books collection
```
- Added a unit test that uses `datastore.pull()` to verify that only a subset of entities are returned for a collection when using a tag
=> MLIBZ-2162: Allow multiple independent datastores on a single collection

src/core/query.js, src/core/query.spec.js
Put docs with the sort field set to `null` at the beginning of the sorted array.
- Added test that checks that fields with a `null` value are sorted to the beginning of the list.
=> MLIBZ-2156: Correctly sort fields that have a null value

test/integration/configs/tests-config.js, test/integration/create-platform-specific-config.js, test/integration/tests/sync.test.js
Add test to sync suite, to check if changes from BL are reflected offline.
@tsvetomir-nedyalkov This shouldn't be merged before the new collection is created with the proper (same as the old collection's) permissions set. And a PreSave cloud code hook is added for the new collection, setting the property from the config, to the expected value (also in the config).
=> Add test for sync suite

src/core/index.js, src/core/polyfills/index.js, src/core/polyfills/object.js
https://kinvey.atlassian.net/browse/MLIBZ-2296
=> MLIBZ-2296: Add polyfill for Object.prototype.assign()

packages/kinvey-html5-sdk/test/config.js, src/core/datastore/sync.spec.js, src/core/datastore/sync/sync-manager.js, src/core/utils/misc.js, test/integration/sync.test.js
MLIBZ-2310. Update local entities after doing a `.push()`, to ensure any BL changes to the entities are reflected locally, for create and update pushes. And for backwards compatibility.
Add the logic for updating local entities with the responses to create and update network requests (the current server items). Refactor `SyncManager` to improve readability.
=> Data stores redesign - fix push() behaviour

packages/kinvey-html5-sdk/test/tasks/serveTests.js, packages/kinvey-html5-sdk/test/tasks/webRunTests.js, test/integration/tests/crud-entity/common-crud.test.js, test/integration/tests/crud-entity/offline-crud.test.js, test/integration/tests/sync.test.js
Add a few integration tests. Change some tests to use the Observable API, instead of promises, to make sure we have that covered on all methods of data stores. Group some tests in a describe block, instead of featuring the method being tested in their names.
Some tests are skipped, as they are about functionality which is not yet implemented.
=> Integration tests additions

src/core/query.js, src/core/query.spec.js
- Added `const PROTECTED_FIELDS = ['_id', '_kmd', '_acl'];`
- Concatenated the specified fields array with the protected fields array
- Added unit test to verify protected fields are not removed when using a query with specified fields
=> MLIBZ-2159: _id field not returned when specifying fields for a query

src/core/datastore/cachestore.spec.js, src/core/datastore/networkstore.js, src/core/datastore/persisters/browser/websql-sql-module.js, src/core/datastore/processors/cache-offline-data-processor.js, src/core/datastore/sync/sync-manager.js, src/core/datastore/sync/sync-state-manager.js, src/core/datastore/syncstore.spec.js, src/core/observable.js, test/integration/tests/crud-entity/common-crud.test.js, test/integration/tests/crud-entity/offline-crud.test.js
**IMPORTANT:** This is to be reviewed only after stage 4, part 1 (PR #227).
This adds improvements as per MLIBZ-2274 and MLIBZ-2275. A couple of small bug fixes, improvements and changes to tests.
Update clear() integration tests and unit tests to reflect the new behaviour - clearing sync items as well as collection entities. Some refactoring and bug fixing for sync, observables and offline storage.
=> Datastores redesign stage 4, part 2 - improvements

packages/kinvey-html5-sdk/src/bundle.js, packages/kinvey-html5-sdk/src/index.js, packages/kinvey-nativescript-sdk/src/bundle.ts, src/core/client.js, src/core/datastore/repositories/index.js, src/core/datastore/repositories/repository-provider.js, src/core/datastore/repositories/storage-provider.js, src/core/index.js, src/core/utils/misc.js, src/html5/client.js, src/html5/index.js, src/html5/offline-data-storage.js, src/nativescript/client.ts, src/nativescript/index.ts, src/nativescript/offline-data-storage.ts
MLIBZ-2329. Change the selection of storage to fit the implementation in master currently. There is also a slight change to an integration test about `clear()`. I separated testing deletion of collection entities from deletion of sync items. This is one of the changes with the current implementation that are coming with the redesign.
Rename the storage enum, expose it in the same way (with only supported storages for the platform).
=> Datastores redesign stage 4, part 3 - storage selection

src/html5/storage/websql.js
During the mono repo move (I believe. this is the commit [here](https://github.com/kinvey/js-sdk/commit/73903fa)), the caching of database connections was removed. This caused problems when making many operations in websql, since each one would "open" the database. We encountered this in the unit tests suite.
Add back the caching of "open" databases.
=> MLIBZ-2350 Revert removal of caching db connections in WebSQL.

src/kinvey.d.ts
Updated definition of `signup()` to allow zero parameters (required to signup as implicit user)
Minor change to `.ts` file.
=> MLIBZ-2314 Updated typescript definitions

package-lock.json, package.json, src/core/polyfills/index.js, src/core/polyfills/object.js
This ticket was about Array.prototype.find missing in the web view of Android 5.1. I've also polyfilled Object.keys() to work as it works in modern v8 environments (not throwing an error when called with an enumerable parameter like string). This is so we can be fully backwards compatible (after the redesign, which fixes a few other compatibility issues) with older web views.
Array.prototype.findIndex is also polyfilled, since it's used, but it hasn't been hit as it's only used in LocalStorage and SessionStorage persisters, and I guess no one has used those in an outdated environment.
Add `core-js` library for polyfills and use them in the corresponding file.
=> MLIBZ-2380 Improve compatibility with older environements

src/core/datastore/cachestore.js, src/core/datastore/sync/sync-manager.js, src/core/datastore/sync/sync-state-manager.js, src/core/datastore/utils/utils.js, src/core/datastore/working-with-data-tests/data-stores-sync-manager.spec.js, test/integration/tests/sync.test.js
Querying for deleted entities is still a bit unclear ([MLIBZ-2177](https://kinvey.atlassian.net/browse/MLIBZ-2177)), so the special case where no query is provided needs to be handled explicitly and this was missing from the `pull()` method.
Also added a tiny optimization for the type of query being built for sync items. This has to do with [the difference](https://hackmd.io/IbBmGMAYFYGYBMC0B2ARgFgIyPeUBORVaVZRWWXLdfTcWZIA) that the collection name of sync items now contains the tag. So the filter needs to match the tagged or untagged collection name (for backwards compatibility), so it has an "or" condition. But when the collection being used doesn't have a tag in the first place, it would result in a redundant "or", so I removed it to speed up inmemory filtering. This can be removed in …
=> MLIBZ-2385 Incorrect sync item count

src/kinvey.d.ts, src/nativescript/kinvey.ts
We are trying to create a convention for all NativeScript plugins to keep configuration data in `<project dir>/app/package.json`.
The values of the configuration data can be safely retrieved at runtime.
The idea of this PR is to read appKey, appSecret and masterSecret from this package.json file. The format there will be:
```JSON
{
"android": {
"v8Flags": "--expose_gc"
},
"main": "main.js",
"name": "tns-template-hello-world-ng",
"version": "3.1.1",
"pluginsData": {
"kinvey-nativescript-sdk": {
"config": {
"appKey": "app_key_value",
"appSecret": "app_key_secret"
}
}
}
}
```
This improves the logic on clients side - the init method can be called without arguments.
The other important improvement is that in Sidekick we can check if there are values for appKey and appSecret in this well known …
=> feat(nativescript): Allow calling Kinvey.init without arguments

src/core/identity/mic.js, src/phonegap/popup.js
The Angular, Angular2, and PhoneGap SDKs all share the same popup class. All the imports expected an exported class named `Popup` but instead it was named `PhoneGapPopup`. This would cause a MIC to not work on environments using these SDKs.
- Rename `PhoneGapPopup` to `Popup`.
- Instantiante the `Popup` class when requesting a code for Mobile Identity Connect login.
=> Fix Mobile Identity Connect Popup Issues

packages/kinvey-phonegap-sdk/src/bundle.js, src/core/datastore/cachestore.spec.js, src/core/datastore/persisters/memory-key-value-persister.js, src/core/request/network.js
Fixes for MLIBZ-2398 and MLIBZ-2405. One was a typo, remaining from before the change in the name of the constant. The other was a suboptimal default value we used in the shorthand for executing an HTTP request. @thomasconner please confirm this is the way it should be used. It's overwritable, but I believe this should be the (aptly named) default always, no?
Fix name of "enum" for platform names. Use shallow copies of entities when using inmemory persistance. Change the default auth parameter of network request config.
=> Beta release bugfixes

src/core/identity/mic.js, src/core/identity/mic.spec.js, src/core/request/network.js
Use the long form MIC `clientID` in the auth header for KAS endpoints
New `AuthType` called `Client` that uses the long-form MIC `clientID`.
Updated unit tests
=> MLIBZ-2399 clientid auth

src/core/datastore/persisters/browser/browser-key-value-persister.js, src/core/datastore/persisters/browser/indexeddb-key-value-store-persister.js, src/core/datastore/persisters/key-value-store-persister.js, src/core/datastore/repositories/repository-provider.js, src/core/datastore/repositories/utils.js, src/core/datastore/sync/sync-manager.js
One of the error messages for WebSQL featured the words "IndexedDB database", so I removed the name of the database for the error - I don't think it brings much value anyways. The error object building (as we discussed before) is pending an overhaul. Also the IndexedDB and SQL persisters need an overhaul as well - they were copied pretty much "as is" to speed up the redesign.
Minor fixes for variable names, remove outdated comments, improve error messages.
=> Minor refactoring

packages/kinvey-nativescript-sdk/src/bundle.ts, src/nativescript/index.ts
The NativeScript SDK overrides the `Files` module to upload files properly using native APIs for iOS and Android. The `Files` module needs to be exported in place of the `Files` module exported from the core to properly upload files using the NativeScript SDK.
- Export the `Files` module from the NativeScript SDK instead of the one from the core.
- Tested manually
=> MLIBZ-2393: Override exported Files module with NativeScript version

packages/kinvey-nativescript-sdk/package.json, packages/kinvey-nativescript-sdk/platforms/ios/app.entitlements
Refer to https://github.com/Kinvey/nativescript-sdk/issues/31 for details on the issue and and proposed fix.
This PR adds a default `app.entitlements` file to the nativescript-sdk.
Tested manually with a MIC sample (https://github.com/tejasranade/EnterpriseSSO)
=> Add default entitlements plist file to nativescript sdk

src/core/query.js
When utilizing a `Cache` collection, requests are failing in this function block due to the `value` being either a string or a boolean, and are being passed into `Object.keys`.
For some reference, when this issue was encountered, the value for `this.filter` was:
```js
{ collection: "GenericUser" }
```
Which is the name of the Cache collection we are calling `find` on. `value`, in this case, will equal `"GenericUser"`, which is breaking when being passed to `Object.keys`.
I haven't done too much digging to see whether this was an issue with how `CacheRequest` is passing the current query, or if this is just an edge case that should be included in this function.. any insight would be great!
- Add a type check to make sure `value` is an object before calling `Object.keys` on it.
=> (Query -> isSupportedOffline) Check that a value is an object before calling Object.keys

packages/kinvey-js-sdk/src/index.js, src/core/datastore/persisters/browser/browser-key-value-persister.js, src/core/datastore/repositories/offline-repositories/inmemory-offline-repository.js, src/core/index.js
This exposes existing repositories, persisters and repositoryProvider from the core. They are not exposed in individual shims. These calsses are available under `Kinvey.DataAccess`. Input is welcome on this namespacing, as it seems classes usually were exposed directly on the Kinvey object. Also advice if this is the best way to expose those classes is also welcome, as I'm not too familiar with the practice here.
Classified `InmemoryOfflineRepository._delete()` and `BrowserKeyValuePersister._buildMasterCollectionName()` as "protected" from "private", as I have advised the guys from Dialexa to override these methods for their purposes and we should know this might break the RN shim, if changed (should they go that route).
=> MLIBZ-2410 Expose data access classes from core SDK

src/core/client.js, src/core/client.spec.js
Allow a user to provide an`instanceId` config option to `init()` that will setup up the Kinvey API and MIC urls correctly.
```javascript
const client = init({
appKey: '<appKey>',
appSecret: '<appSecret>',
instanceId: '<my-subdomain>'
});
client.apiHostname // https://<my-subdomain>-baas.kinvey.com
client.micHostname // https://<my-subdomain>-auth.kinvey.com
```
- Support config option `instanceId` in `client.js` constructor.
- Added a test to `client.spec.ts` that checks if an error is thrown if `instanceId` is anything but a string
- Added a test to `client.spec.ts` that checks if an `instanceId` is provided that the `apiHostname` and `micHostname` are correct.
=> MLIBZ-2332: Add support for Instance ID

src/core/datastore/cachestore.js, src/core/datastore/cachestore.spec.js, src/core/datastore/processors/cache-offline-data-processor.js, src/core/datastore/utils/utils.js, src/core/datastore/working-with-data-tests/cache-offline-data-processor.spec.js, src/core/datastore/working-with-data-tests/data-stores-sync-manager.spec.js, test/integration/tests/sync.test.js
Remove the implicit push() calls in DataStore.pull(), CacheStore.find(), CacheStore.findById(), CacheStore.count(), CacheStore.group(). This removes potentially unexpected behaviour and improves the number of local reads from 2 to 4, to always 2.
Remove the count-push-count flow from CacheStore read-based ops. They do count and return an error if there are entities pending push. Otherwise proceed with their regular flow.
Put the check for entities pending push after the return of the offline result - it isn't being impeded by the entities pending sync.
Update tests accordingly.
Change the error message - input welcome.
=> MLIBZ-2131 Remove implicit push() calls

src/core/identity/mic.js, src/core/identity/mic.spec.js
Adds validation that checks if a `redirectUri` provided to `mic.login()` is provided and a string.
- Return a rejected `Promise` if the `redirectUri` provided to `mic.login()` is invalid.
- Added a test that checks that `mic.login()` fails when no `redirectUri` is provided.
- Added a test that checks that `mic.login()` fails when `redirectUri` is not a string.
=> MLIBZ-2422: Validate MIC RedirectUri

src/core/client.js, src/nativescript/secure/secure.ios.ts
JS SDK using the same params used by the Swift SDK
Using the same query params used by our Swift SDK
=> iOS Keychain conformance

src/core/datastore/processors/cache-offline-data-processor.js, src/core/datastore/sync/sync-manager.js, test/integration/tests/delta-set.js
1. Enable deltaset
2. Create 5 items
3. Pull - there are now 5 items in cache
4. Delete 3 items
5. Pull - the request returns 3 items in deleted array
6. Check cached collection
The 3 items deleted from the server are deleted in the cached collection.
The items are still present in the cached collection.
- Use `contains()` instead of `containsAll()` for delete query
- Add integration test
=> MLIBZ-2517: Use correct query filter to delete multiple entities when using Server Side Delta Set

src/core/datastore/sync/sync-manager.js, src/core/datastore/working-with-data-tests/sync-manager.spec.js, test/integration/tests/sync.test.js
1. Create a few items in the server and pull them locally
2. Enable auto-pagination
3. Delete a few items in the server 
4. Pull with auto-pagination
Items are deleted locally
Items are not deleted locally
- Remove all entities in the cache for a collection before loading pages using auto pagination
- Updated the existing unit test for this scenario
- Added an integration test for this scenario
=> MLIBZ-2520: Delete items properly with Auto Pagination

src/core/request/network.js, src/core/user/user.js, src/core/user/user.spec.js
1. Log into any web app using kinvey-html5-sdk
2. Check the value of a field in the current user's record to make sure it is non-empty – both in the Console -> Identity -> Users page, and in the client app.
3. In the Console -> Identity -> Users page, manually update/erase the value of the field.
4. In the client app, call user.me() on the current user - the saved active user in the SDK is not updated with the deleted property - the code here merges the updated fields but does not remove deleted properties.
The field value should be empty/deleted from the current user's data in the client.
The field value still exists that was empty/deleted.
- Remove merging of data returned in the response from the `/_me` endpoint. The active user data is now replaced with the data returned in the …
=> MLIBZ-2503: User.me() does not delete newly-empty fields on the SDK

src/kinvey.d.ts
The TypeScript definitions for `User.lookup()` function state that the function returns a `Promise` when it really returns an `Observable`.
- Update the TypeScript definitions file to state that the `User.lookup()` function returns an `Observable`.
- No testing needed. This was a documentation change.
=> MLIBZ-2455: TypeScript Definitions wrong for User.lookup()

package-lock.json, src/core/client.js, src/core/datastore/repositories/offline-repositories/inmemory-offline-repository.js, src/core/utils/misc.js
Clearing the cache used by the datastore will clear the stored active user when the SDK is set to use [LocalStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) as the persistence adapter for the datastore cache.
- Do not clear the active user collection when clearing the datastore cache and using the local storage adapter.
- Add integration test to verify
=> MLIBZ-2450: Don't clear the active user when using local storage

src/core/datastore/sync.spec.js, src/core/datastore/sync/sync-manager.js
When an entity is created offline it will set the property `_kmd.local` to `true`. This needs to be removed before sending it to the backend. Currently it is not resulting in the following error:
```
{
"error":"DataLinkConnectorError",
"debug":"Unable to insert record. Error message = {\"_errors\":[{\"_errorMsg\":\"ERROR condition: An incomplete client request. (8020) (7211)\",\"_errorNum\":8020}]}",
"description":"The DataLink request did not complete. See debug message for details."
}
```
- Remove `_kmd.local`
- Added unit test to verify `_kmd.local` is removed
=> MLIBZ-2526: Remove _kmd.local

packages/kinvey-angular-sdk/src/bundle.js, packages/kinvey-angular2-sdk/src/bundle.js, packages/kinvey-html5-sdk/src/bundle.js, packages/kinvey-phonegap-sdk/src/bundle.js, src/core/files.js, src/html5/files.js, src/html5/index.js, src/nativescript/filestore/common.ts, test/integration/tests/files-common.tests.js
To prevent errors the SDK should calculate the file size before it is uploaded. The file size should be then verified that we don't try and create a file with a size of 0.
- Calculate file size on HTML5. Export HTML5 FilesStore correctly.
- Verify file size before it is uploaded.
- _Add integration tests for related changes (TBD)_
=> MLIBZ-2575: Calculate file size

src/core/request/network.js
A MIC refresh token request is suppose to use the `clientId` value used to create the MIC session.
- Change auth type to `AuthType.Client` and pass `clientId` used to create MIC session
=> MLIBZ-2580: Use correct Authorization header value for MIC refresh token request

package-lock.json, package.json
Setting the body for a `GET` request made with an Android app on [NativeScript](https://www.nativescript.org) results in the following error:
```
System.err: java.net.ProtocolException: method does not support a request body: GET
System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(Unknown Source:0)
System.err:     at org.nativescript.widgets.Async$Http$RequestOptions.writeContent(Async.java:313)
System.err:     at org.nativescript.widgets.Async$Http$HttpRequestTask.doInBackground(Async.java:536) …
```
=> MLIBZ-2586: Use PubNub fork as dependency

package-lock.json, package.json, src/core/request/network.js
A response to an API request can result in a `401` which will attempt to refresh a MIC access token. When multiple requests are made in parallel this would cause multiple attempts to refresh the MIC access token. This caused an invalid state that was unrecoverable.
This PR only allows one attempt to refresh a MIC access token while queuing up any other API request made while the refresh attempt is made. Once the refresh attempt completes then the queued requests will be retried.
- Queue up pending API requests when refreshing a MIC access token
=> MLIBZ-2585: Queue requests when in the middle of refreshing a MIC access token

src/core/datastore/cachestore.js, src/core/datastore/cachestore.spec.js, src/core/datastore/datastore.doc.js, src/core/datastore/sync/sync-manager.js, src/core/datastore/syncstore.spec.js, src/core/datastore/working-with-data-tests/data-stores-sync-manager.spec.js, src/core/datastore/working-with-data-tests/sync-manager.spec.js
All items in the sync queue should be pushed to the backend when given the opportunity. A `query` should not be allowed to push a subset of the sync queue.
- Remove use of a `query` to push a subset of the sync queue.
- Update reference docs.
- Update related unit tests.
=> MLIBZ-2604: Ignore query when executing push()

src/html5/http.js, src/nativescript/http.ts, src/node/http.js
**Steps To Reproduce:**
1. Stream a file with ttl = 0: 
```js
Kinvey.Files.download(fileId, { stream: true, ttl: 0 });
```
2. Try to download the file using the expired `__downloadURL_`: 
```js
Kinvey.Files.downloadByUrl(result._downloadURL);
```
**Expected Result:** The error function is called with the error from the server.
**Actual Result:** The success function is called with a string, containing an XML from the server:
```xml
<?xml version='1.0' encoding='UTF-8'?><Error><Code>ExpiredToken</Code><Message>The provided token has expired.</Message><Details>Request has expired: 1523979099</Details></Error>
```
- Reject with error from Network response.
- Only send X-Kinvey-Device-Information header to a kinvey.com endpoint.
=> MIBZ-2453: Kinvey.Files.downloadByUrl should call the error function if the server returns an error

src/html5/files.js, src/nativescript/filestore/common.ts
Tested with 3.10.3 in the HTML5 shim. The tests for upload in _test/integration/tests/files-common.tests.js_  in _QA-196_tests_files_ branch can be accommodated in order to reproduce the issue.
**Steps To Reproduce**:
1. Try to upload a file with:
```js
Kinvey.Files.upload(file, null, { timeout: 100000 })
```
**Expected Result:** The operation succeeds
**Actual Result:** The following error:
```js
TypeError: Cannot read property 'filename' of null
at FileStore.transformMetadata (http://localhost:64320/packages/kinvey-html5-sdk/dist/kinvey-html5-sdk.js:33946:41)
at FileStore.upload (http://localhost:64320/packages/kinvey-html5-sdk/dist/kinvey-html5-sdk.js:33894:23)
at Object.testFileUpload (http://localhost:64320/test/integration/tests/utilities.js:252:18)
at Context.it.only …
```
=> MLIBZ-2498: Kinvey.Files.upload() returns an error if the submitted metadata = null

package-lock.json, package.json, packages/kinvey-angular2-sdk/kinvey.d.ts, packages/kinvey-nativescript-sdk/kinvey.d.ts, src/core/observable.js, src/core/utils/misc.js
This fixes #https://github.com/Kinvey/nativescript-sdk/issues/34.
- Update [rxjs](https://github.com/ReactiveX/rxjs) to version 6.
=> Update rxjs to version 6

packages/kinvey-angular2-sdk/kinvey.d.ts, packages/kinvey-nativescript-sdk/kinvey.d.ts
The Typescript definitions for instanceId option is missing, resulting in error `"instanceId is not assignable to parameter of type clientConfig"`
- Added `instanceId?: string` to the TypeScript definitions
=> MLIBZ-2532: Missing instanceId in TypeScript definitions for Kinvey.init()

src/core/datastore/cachestore.spec.js, src/core/datastore/processors/cache-offline-data-processor.js, src/core/datastore/working-with-data-tests/cache-offline-data-processor.spec.js
Use `datastore.find()` to find entities on the backend that match a query. Make sure the entities returned don't contain all the matched properties in the query.
```json
[
{
"name": "John",
"userId": "1"
}
];
```
```javascript
const query = new Kinvey.Query();
query.equalTo('date', '7-25-2018');
query.equalTo('userId', '1');
const datastore = Kinvey.DataStore.collection('UserProfiles');
const entities = datastore.find(query);
// entities equals above json
```
- Return data from network call.
- Added test to check that data is still returned when the use case described above is encountered.
=> MLIBZ-2630: Not all entities returned from DataStore.find()

src/core/datastore/cachestore.spec.js, src/core/datastore/repositories/network-repository.js
Users are able to provide custom properties that are sent in the `x-kinvey-custom-request-properties` header.
- Fix order of arguments passed to function when creating an entity.
- Add unit tests for checking that the `x-kinvey-custom-request-properties` header is set
=> MLIBZ-2665: Send custom properties

packages/kinvey-nativescript-sdk/push.d.ts, packages/kinvey-nativescript-sdk/src/push/push.ios.ts
- Update TypeScript definitions for Push to allow options to be provided to `unregister()`
- Fix boolean logic for registering interactive settings for iOS push
=> MLIBZ-2660: Fix iOS Push

packages/kinvey-nativescript-sdk/lib/before-checkForChanges.js
This reverts the changes made from [this discussion](
https://github.com/Kinvey/js-sdk/pull/305#discussion_r213193683).
- Don't throw an error if a `redirectUri` is not provided in the `package.json`
=> MLIBZ-2366: NativeScript MIC

src/core/files.js, src/core/request/network.js, src/nativescript/http.ts
- Do not call `toString()` on the response data for file downloads.
=> MLIBZ-2543: Fix encoding issue when downloading files via the NativeScript SDK

packages/kinvey-nativescript-sdk/webpack.config.android.js
=> MLIBZ-2695: Do not include tns-core-modules in NativeScript Android SDK bundle

lerna.json, src/html5/popup.js
`loginWithMIC()` uses a popup when on a web browser to display the identity providers login page. An interval is setup to poll this popup for url changes. Once the popup redirects after a successful login the interval will parse the code received from the redirect url and provide it to the SDK.
While the user is attempting to login, the url of the popup is on a different domain of the hosted application that initiated the login. This causes an error when checking the url of the popup that has to be handled and thrown out.
This change handles the error specific thrown by Microsoft Edge when trying to access the url for the popup.
- Handle the specific error thrown by Microsoft Edge for `loginWithMIC()`
- This was tested manually on Microsoft Edge running on a Windows 10 VM and Google …
=> MLIBZ-2671: Fix MIC on Microsoft Edge

packages/kinvey-nativescript-sdk/platforms/android/AndroidManifest.default.xml, src/nativescript/http.ts
For the new `X-Kinvey-Device-Info` header, we were using the `tns-core-modules/connectivity` module to gather the network connection info. On Android you need to add the `<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />` to the `AndroidManifest.xml` otherwise an error is thrown.
I had added this permission but the error is still thrown occasionally. Since it is not critical I am removing the use of the module for now.
- Remove the use of  the `tns-core-modules/connectivity` module
- Remove `<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />` from the `AndroidManifest.xml`
=> Remove use of tns-core-modules/connectivity

src/core/user/user.js, src/core/user/user.spec.js, src/core/user/utils.js
Preserve the data stored in `_socialIdentity` on the device over what is returned when updating and calling the `/me` endpoint.
- Merge the `_socialIdentity` properly
- Add unit test that checks if the `_socialIdentity` is correct when updating a user
=> MLIBZ-2656: Merge _socialIdentity property on user

src/core/user/user-mock.js, src/core/user/user.js, src/core/user/user.spec.js, src/core/user/utils.js
__Steps to reproduce:__
1. Login with MIC in an app2. Call `User.me()`
__Expected result:__ The result of `User.me()` does not override the `activeUser` metadata set when login
__Actual result:__ The result of `User.me()` overrides the `activeUser` metadata set when login
- Merge `_socialIdentity` metadata when `User.me()` is called
- Added unit test
=> MLIBZ-2690: Calling me() overrides the active user data for _socialIdentity

src/core/files.js
__Steps To Reproduce__:
1. Try to download a file with:
```javascript
Kinvey.Files.findById();
```
__Expected Result:__ A meaningful error message, explaining that the id is required. The same problem is valid for `Kinvey.Files.download()`
__Actual Result:__ The following error:
```
TypeError: Cannot read property 'mimeType' of undefined
at http://localhost:64320/packages/kinvey-html5-sdk/dist/kinvey-html5-sdk.js:33816:33
at tryCatch (http://localhost:64320/packages/kinvey-html5-sdk/dist/kinvey-html5-sdk.js:967:12)
at invokeCallback (http://localhost:64320/packages/kinvey-html5-sdk/dist/kinvey-html5-sdk.js:982:13)
at http://localhost:64320/packages/kinvey-html5-sdk/dist/kinvey-html5-sdk.js:728:16
at MutationObserver.flush (http://localhost:64320/packages/kinvey-html5-sdk/dist/kinvey-html5- …
```
=> MLIBZ-2497: Return correct error message if Files.findById() is called without a file id

packages/kinvey-nativescript-sdk/lib/before-preview-sync.js, packages/kinvey-nativescript-sdk/package.json, packages/kinvey-nativescript-sdk/platforms/android/AndroidManifest.default.xml, src/nativescript/popup/popup.ios.ts, src/nativescript/user.js
Conform Kinvey-sdk with NativeScript preview application. 
MIC login improvements.
Includes:
* **Improvement** Add before-preview-sync hook  - this hook will fire whenever a user scans a QR code displayed in the console from a `tns preview` command. It will warn the user that their application might not work as expected in case they do not have the {N} Preview app uri scheme
* **Improvement** Implement preview app check - kinvey {N} sdk now detects at runtime whether running inside {N} Preview app. If this is the case disregard any arguments passed to `loginWithMIC` and use the preview app scheme `nsplayresume` instead 
* **Fix(iOS):** Visualize login page in topmost `UIViewController` - prior to this the login page was displayed on the root `UIViewController`. Whenever the root …
=> Conform with NativeScript preview application

packages/kinvey-nativescript-sdk/platforms/android/include.gradle, packages/kinvey-nativescript-sdk/push.d.ts, packages/kinvey-nativescript-sdk/src/push/push.android.ts, packages/kinvey-nativescript-sdk/src/push/push.d.ts, packages/kinvey-nativescript-sdk/src/push/push.ios.ts
The notification callbacks on iOS and Android behave differently: iOS receives a JSON object and Android a data String and native Notification object. Furthermore, on Android the callback is not invoked when the app is not in the foreground (which is probably mostly the case). Developers are advised to create a `resumeEvent` listener and parse the launch Intent to get the Andoir background notification data.
To overcome this situation, I've added a new notification callback handler which has the same return object for both iOS and Android. For backward compatibility sake I've not touched the current iOS and Android specific callbacks, so users can migrate to new callback whenever they fancy. Fixes https://github.com/Kinvey/nativescript-sdk/issues/43.
- Added `notificationCallback` which …
=> New notification callback handler for easier developer usage

src/core/datastore/networkstore.js, src/core/datastore/networkstore.spec.js
If you call `collection.create()` or `collection.update()` without an entity it will return resolve with `null`.
If you call `collection save()` without an entity then a `TypeError: Cannot read property '_id' of undefined` is thrown.
- Add validation to throw an error whenever an entity is not provided to save(), create(), and update()
=> MLIBZ-2706: Add validation for save(), create(), and update()

src/nativescript/kinvey.ts
The idea of this PR is to read `instanceId` from this package.json file.
In Kinvey Studio we can check if there is value for `instanceId` and if user has Single-Tenant Cloud Instance to enter the correct value.
ping @thomasconner
=> Respect instanceId from package.json.

packages/kinvey-nativescript-sdk/README.md
Makes change related to https://github.com/Kinvey/nativescript-sdk/pull/46.
=> Fix documentation link in kinvey-nativescript-sdk README

src/core/user/user.js, src/core/user/user.spec.js
When `me()` is called and no active user exists `null` is returned and no `_me` request is sent instead of throwing a `NoActiveUserError`.
- Throw `NoActiveUserError` when no active user exists and `me()` is called
=> MLIBZ-2708: Throw NoActiveUserError when no active user exists and me() is called

src/core/live/live-service.js
NativeScript apps are often put in the background or experiencing a loss of network connectivity for a short time period. These states will cause the PubNub client to disconnect. To fix this issue we attempt to reconnect the PubNub client when the app is resumed or network connectivity, However, this also caused a problem where messages would begin doubling or even tripling. To fix this issue we have added the `dedupeOnSubscribe` flag to the PubNub client config.
- Added `dedupeOnSubscribe` flag to PubNub client config.
=> MLIBZ-2732: Fix multiple messages being received when PubNub is reconnected

packages/kinvey-nativescript-sdk/lib/before-preview-sync.js
The projectIdentifier is the identifier of the NS application that the user is working on, not the identifier of the preview app. However, we can check which preview app the NS application is working with by checking the previewAppSchema of the NS application.
Fix the warn message to pint the correct resume scheme.
=> Print the correct warn message for resume scheme

packages/nativescript-sdk/src/nativescript/popup/popup.android.ts
As the `kinvey-nativescript-sdk` package uses the old Android Support Libraries, it will not be compatible with the upcoming NativeScript 6.0 release which will use [AndroidX by default](https://www.nativescript.org/blog/support-for-androidx-in-nativescript). The changes from this PR, make the package compatible with the AndroidX library (NS 6.0) and with the old libraries (NS before 6.0).
Use CustomTabs on android from the AndroidX Library if it is available (when project uses tns-android@6.0) or use it from the old support library otherwise (when project uses tns-android version before 6.0).
=> fix: androidx compatibility

packages/js-sdk/src/init.ts
=> MLIBZ-2961: Throw error with deprecation message for initialize()

packages/nativescript-sdk/package-lock.json, packages/nativescript-sdk/package.json
Currently, in order to use `kinvey-nativescript-sdk`, you need to have git installed on your machine. The problem is that one of the dependencies (pubnub) is declared with `git+https`.
Replace this with direct url to github, which is a .tgz file. This way you'll be able to install `kinvey-nativescript-sdk` without having `git` on the machine.
NOTE: This should also resolve an issue with npm 5.x.x versions. The issue is that `pubnub` will not be install with npm 5.6.0 in case you execute the following steps:
```
npm i kinvey-nativescript-sdk // this will also generate package-lock.json
ls -l node_modules/pubnub // this should show the dir exists
rm -rf node_modules
npm i
ls -l node_modules/pubnub // this command will fail
```
=> fix: do not require git when using the kinvey-nativescript-sdk

packages/nativescript-sdk/nativescript-hook-scripts/before-checkForChanges.js, packages/nativescript-sdk/nativescript-hook-scripts/before-preview-sync.js
In NativeScript 6.0.0 there's a major refactoring in CLI that will require changes in most of the plugin hooks.
The major changes are the hookArgs injected by CLI for each hook - they are changed, so some of the properties used from them, should be taken from different property.
The other major change is the injected data - in the function used as hook, you can use any service registered in CLI's bootstrap and CLI will pass it to the hook.
Several of the services are now renamed or deleted, so hooks using them should be migrated. Such service is platformsData.
The last major change is that some logger methods are deleted (they've been deprecated).
The current PR makes the hooks of this plugin compatible with the both 6.0.0 and old releases of NativeScript.
=> feat: make hooks compatible for Nativescript 6.0 release

packages/js-sdk/package.json, packages/js-sdk/src/query.ts, packages/js-sdk/test/query.spec.ts
The `Query` class will set `{ sort: { "undefined"; 1 }` if you don't provide a value to `ascending()`. The same is true for `descending()` too.
- Verify arguments to `ascending()` and `descending()`.
- Add unit tests
- Update test scripts to run all unit tests
=> MLIBZ-2700: Verify arguments for ascending() and descending() on Query class

packages/js-sdk/src/query.ts, packages/js-sdk/test/query.spec.ts
If a field is not provided to exists then `{ "undefined": { $exists: true }}` is added as a filter.
- Verify arguments to `addFilter()`
- Add unit tests
=> MLIBZ-2701: Verify arguments to Query.exists()

packages/nativescript-sdk/package.json
When kinvey-nativescript-sdk is used in a non angular nativescript app, there is a warning in the terminal that peer dependency of @angular/core is missing. This confuses users and the dependency is not really needed in their case.
In nativescript plugins we add angular only as dev dependency, and it is required only when you use <your-plugin>/angular. I doubt that anyone would use the angular implementation in a non angular app.
Remove @angular/core from dev dependencies of kinvey-nativescript-sdk
=> chore: remove angular as peer dependency from nativescript sdk

packages/nativescript-sdk/src/nativescript/popup/popup.ios.ts
utils.ios.getter was deprecated in NativeScript.
- Removed getter method and unused import.
=> fix: getter is deprecated

.cirrus.yml, packages/js-sdk/package-lock.json, packages/react-native-sdk/.eslintrc, packages/react-native-sdk/.gitignore, packages/react-native-sdk/package-lock.json, packages/react-native-sdk/package.json, packages/react-native-sdk/src/__tests__/push.spec.ts, packages/react-native-sdk/src/push.ts, packages/react-native-sdk/tsconfig.json
This PR adds support to the `kinvey-react-native-sdk` for push notifications using [react-native-push-notification](https://github.com/zo0r/react-native-push-notification) package.
=> Add support for push notifications to React Native SDK

packages/js-sdk/src/datastore/sync.ts, packages/js-sdk/test/datastore/syncstore.spec.ts
If a generic error occurs with the multi-insert request during `push`, the whole push operation is rejected.
We must catch that error, continue pushing any other changes, and comply to the known result format from the `push` operation. This means adding a result entry for each object that failed to be inserted.
=> KDEV-861: Do not reject push on multi-insert generic error

packages/js-sdk/src/datastore/cachestore.ts, packages/js-sdk/src/datastore/sync.ts, packages/js-sdk/test/datastore/autostore.spec.ts
The previous fix #567 should be applied only for `push` function, because it may perform different CRUD actions and should not stop on first error. For other operations like create or update, the general error should be thrown immediately.
=> KDEV-865: Catch general errors and aggregate them only for push function

packages/nativescript-sdk/README.md
"@next" points to non-existant resource in Thomas Conner's github.
=> Update README.md - remove @next reference

packages/html5-sdk/package-lock.json, packages/html5-sdk/package.json
Update `lodash` to version **4.17.19** in order to resolve the two low vulnerabilities in the HTML SDK
=> Updated lodash in order to resolve the two low vulnerabilities

packages/nativescript-sdk/package-lock.json, packages/nativescript-sdk/package.json, packages/nativescript-sdk/src/nativescript/push.ts
Importing
```ts
import { firebase, messaging } from '@nativescript/firebase';
```
Is being compiled by webpack expecting `@nativescript/firebase/firebase.js` to have a `messaging` export, but there is no such export and the import fails.
=> KDEV-1451: {N} SDK - Fix webpack failing to find firebase messaging package

packages/js-sdk/src/datastore/autostore.ts, packages/js-sdk/src/datastore/cachestore.ts, packages/js-sdk/src/query.ts, tests/integration/specs/common/autostore.spec.js, tests/integration/specs/utils.js
AutoStore now uses the specified paging settings (skip, limit) and projection, when performing a `.find()`. This will bring about a side effect that fetching pages in a non-sequential manner could result in discrepancies between what's been fetched and what is stored for offline use. We will be addressing this issue in a planned later redesign of the AutoStore.
- Extract the logic to be used for `.find()` in a separate method and preserve the current behaviour of `.pull()` and `CacheStore.find()`
- Use the old `AutoStore.find()` logic when using delta set, for the time being
- Fix a wrong validation for `AutoStore.group()` which prevented its use
- `AutoStore.find()` with a projection (the `fields` query option) fetches all fields from the server, stores them offline and then prunes …
=> KDEV-721: Use all Query instance features when doing an autoStore.find()

packages/js-sdk/src/datastore/cachestore.ts, tests/integration/specs/common/autostore.spec.js
Ref: https://github.com/Kinvey/js-sdk/pull/589 
Opening a new PR since CI cannot run for code from forks because of secrets. Thanks to @itamitegama for reporting the issue and opening a PR.
When doing a pull() with auto pagination enabled, when the server returns no items, an initial value is not provided to .reduce(), causing an unhandled error.
Provide an initial value to `.reduce`. Add a test.
=> KDEV-1645: Fix pull() for offline stores

.cirrus.yml
HTML5 integration tests were failing with:
```
Cannot start Chrome
/tmp/cirrus-ci-build/node_modules/chromium/lib/chromium/chrome-linux/chrome: error while loading shared libraries: libxshmfence.so.1: cannot open shared object file: No such file or directory
```
=> Add libxshmfence1 library to CI environment for HTML5 tests

packages/angular-sdk/src/user.service.ts, packages/html5-sdk/src/index.ts, packages/js-sdk/src/index.ts
* The problem was that there were references to the (core) js sdk in the angular sdk. These references led to the changed folder structure. The interfaces are now exported from the js sdk and then from the html5 sdk to the angular sdk.
=> KDEV-1770: Fix the angular build

tests/integration/nativescript/scripts/test.js, tests/integration/specs/common/mfa.spec.js, tests/integration/specs/common/users.spec.js, tests/integration/specs/utils.js
1. Refactored 'createVerifiedAuthenticator' and 'removeAuthenticator' to use the sdk as they hadn't worked in {N}
2. Fixed totp.js "Buffer is not defined" error by adding a hack with a polyfill for 'buffer'.
=> Fix {N} MFA tests

packages/react-native-sdk/package-lock.json, packages/react-native-sdk/src/storage/asyncStorage.ts
Usage of `AsyncStorage` has been optimized by storing each document as a separate key-value pair, instead of storing the whole collection as one value and parsing it for every operation. This was especially inefficient for operations "by id".
It was also necessary to change the key format from using `.` as separator to using `:` instead, because of the tagged collections functionality, which uses `.` as part of the collection name and this led to collisions.
=> KDEV-1897: React-native storage optimization

packages/angular-sdk/CHANGELOG.md, packages/angular-sdk/package-lock.json, packages/angular-sdk/package.json, packages/html5-sdk/CHANGELOG.md, packages/html5-sdk/package-lock.json, packages/html5-sdk/package.json, packages/js-sdk/CHANGELOG.md, packages/js-sdk/package-lock.json, packages/js-sdk/package.json, packages/nativescript-sdk/CHANGELOG.md, packages/nativescript-sdk/package-lock.json, packages/nativescript-sdk/package.json, packages/node-sdk/CHANGELOG.md, packages/node-sdk/package-lock.json, packages/node-sdk/package.json, packages/react-native-sdk/CHANGELOG.md, packages/react-native-sdk/package-lock.json, packages/react-native-sdk/package.json
I have pushed kinvey-js-sdk 6.0.1 to NPM without the latest changes. This required a bump in all dependent shims to fix the issue.
=> Npm audit update versions

packages/js-sdk/src/http/request.ts, packages/js-sdk/src/http/session.ts, packages/js-sdk/test/mic/session-management.test.ts, tests/integration/specs/common/users.spec.js, tests/integration/specs/utils.js
The PR clears the active user when an InvalidCredentials error is received and MIC is not involved. Essentially, this code is present in the latest SDK version. What is different is the missing call to the logout endpoint which has no way of succeeding.
=> KDEV-2482: Clear session on InvalidCredentials error

packages/nativescript-sdk/package-lock.json, packages/nativescript-sdk/package.json
It looks like the {N} sdk uses an older version of nativescript-sqlite - 2.6.4, which causes app crashes for newer iOS versions - https://github.com/NathanaelA/nativescript-sqlite/issues/171
We should update it to 2.8.6, which seems to be working.
=> KDEV-2626: Update sqlite to fix sdk crash for iOS

packages/nativescript-sdk/package-lock.json, packages/nativescript-sdk/package.json
1. Updated the used _pubnub_ version - the changes are in https://github.com/Kinvey/pubnub-javascript/pull/12. 
After the release of _pubnub-javascript_, will be created a new "not dev" tag, which will be updated here too.
2. Updated minimist from 1.2.5 to 1.2.6
Note: The update of pubnub is reverted due to problems on Android.
=> KDEV-2620: Fixed npm security

tests/integration/clean.js, tests/integration/nativescript/package.json
1. Fixed iOS tests to run successfully (even on simulator) as they were failing due to:
- https://github.com/NativeScript/NativeScript/issues/9840
- https://github.com/NativeScript/NativeScript/issues/9907
2. Fixed tear down not to execute all delete requests at once, as it was causing problems if there were 100-200 entities for a deletion
=> KDEV-2638: Fixed {N} iOS tests and the parallel requests bomb in teardown
